import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/context/AuthContext";
import { tripsService, Trip } from "@/services/trips";
import { ItineraryBuilder } from "@/components/trips/ItineraryBuilder";
import { toast } from "sonner";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { Navigate } from "react-router-dom";

interface ItineraryDay {
  dayNumber: number;
  activities: string;
  notes: string;
}

export default function PlanTrip() {
  const navigate = useNavigate();
  const { isAuthenticated, isLoading } = useAuth();
  
  const [destination, setDestination] = useState("");
  const [description, setDescription] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [budget, setBudget] = useState("");
  const [days, setDays] = useState<ItineraryDay[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);

  if (isLoading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center h-64">
          <p className="text-muted-foreground">Loading...</p>
        </div>
      </DashboardLayout>
    );
  }

  if (!isAuthenticated) {
    return <Navigate to="/login" />;
  }

  const calculateDays = () => {
    if (startDate && endDate) {
      const start = new Date(startDate);
      const end = new Date(endDate);
      return Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)) + 1;
    }
    return 0;
  };

  const autoGenerateDays = () => {
    const numDays = calculateDays();
    if (numDays <= 0) {
      toast.error("Please select valid start and end dates");
      return;
    }

    const newDays: ItineraryDay[] = [];
    for (let i = 1; i <= numDays; i++) {
      newDays.push({
        dayNumber: i,
        activities: "",
        notes: "",
      });
    }
    setDays(newDays);
    toast.success(`Generated ${numDays} days for your trip`);
  };

  const handleAddDay = () => {
    const nextDayNumber = days.length > 0 ? Math.max(...days.map(d => d.dayNumber)) + 1 : 1;
    setDays([...days, { dayNumber: nextDayNumber, activities: "", notes: "" }]);
  };

  const handleUpdateDay = (dayNumber: number, activities: string, notes: string) => {
    setDays(days.map(day =>
      day.dayNumber === dayNumber ? { ...day, activities, notes } : day
    ));
  };

  const handleRemoveDay = (dayNumber: number) => {
    setDays(days.filter(day => day.dayNumber !== dayNumber));
  };

  const handleSaveTrip = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!destination || !startDate || !endDate) {
      toast.error("Please fill in destination and dates");
      return;
    }

    setIsSubmitting(true);
    try {
      const trip = await tripsService.createTrip(
        destination,
        startDate,
        endDate,
        description || undefined,
        budget ? parseFloat(budget) : undefined
      );

      // Add itinerary days
      for (const day of days) {
        await tripsService.addItinerary(
          trip.id,
          day.dayNumber,
          day.activities || undefined,
          day.notes || undefined
        );
      }

      toast.success("Trip created successfully!");
      navigate(`/trips/${trip.id}`);
    } catch (error: any) {
      toast.error(error.message || "Failed to create trip");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto py-8 px-4">
        <div className="mb-8">
          <h1 className="text-3xl font-bold">Plan Your Trip</h1>
          <p className="text-muted-foreground mt-2">
            Create a new trip with daily itinerary
          </p>
        </div>

        <form onSubmit={handleSaveTrip} className="space-y-6">
          {/* Trip Details */}
          <Card>
            <CardHeader>
              <CardTitle>Trip Details</CardTitle>
              <CardDescription>Basic information about your trip</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-2">Destination</label>
                <Input
                  placeholder="e.g., Cape Coast, Ghana"
                  value={destination}
                  onChange={(e) => setDestination(e.target.value)}
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">Description</label>
                <Textarea
                  placeholder="Describe your trip purpose and interests..."
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={3}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium mb-2">Start Date</label>
                  <Input
                    type="date"
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-2">End Date</label>
                  <Input
                    type="date"
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    required
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">Budget (Optional)</label>
                <Input
                  type="number"
                  placeholder="0.00"
                  value={budget}
                  onChange={(e) => setBudget(e.target.value)}
                  step="0.01"
                  min="0"
                />
              </div>

              {startDate && endDate && (
                <div className="bg-muted p-3 rounded-lg">
                  <p className="text-sm">
                    Trip duration: <span className="font-semibold">{calculateDays()} days</span>
                  </p>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={autoGenerateDays}
                    className="mt-2"
                  >
                    Auto-generate Daily Itinerary
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Itinerary */}
          <Card>
            <CardHeader>
              <CardTitle>Itinerary</CardTitle>
              <CardDescription>Plan activities for each day</CardDescription>
            </CardHeader>
            <CardContent>
              <ItineraryBuilder
                days={days}
                onAddDay={handleAddDay}
                onUpdateDay={handleUpdateDay}
                onRemoveDay={handleRemoveDay}
              />
            </CardContent>
          </Card>

          {/* Actions */}
          <div className="flex gap-3">
            <Button
              type="submit"
              disabled={isSubmitting}
              className="flex-1"
            >
              {isSubmitting ? "Saving..." : "Save Trip"}
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate("/dashboard")}
            >
              Cancel
            </Button>
          </div>
        </form>
      </div>
    </DashboardLayout>
  );
}
